#!/bin/bash

# 当前目录
CUR_DIR=$(cd "$(dirname "$0")"; pwd)
# 脚本名称
SCRIPT_NAME="$(basename "$0")"
# 脚本版本
SCRIPT_VERSION="0.0.1"

# 全局防火墙链名定义
readonly MB_DNS_CHAIN="MERLINKBOX_DNS"
readonly MB_PROXY_CHAIN="MERLINKBOX_PROXY"
readonly MB_ONESELF_CHAIN="MERLINKBOX_ONESELF"
readonly MB_DNS_CHAIN_V6="MERLINKBOX_DNS_V6"
readonly MB_PROXY_CHAIN_V6="MERLINKBOX_PROXY_V6"
readonly MB_ONESELF_CHAIN_V6="MERLINKBOX_ONESELF_V6"

# sing-box 监听的 TPROXY 端口
readonly MB_TPROXY_PORT=65002
# iptables 打标值与 ip rule 匹配值（一个32位无符号整数, 建议1到255）
readonly MB_FWMARK=168
# 自定义本地路由表编号 (1到32767)
readonly MB_ROUTE_TABLE=111
# 必须在 sing-box 的 outbound 中配置 （一个32位无符号整数, 建议1到255）
readonly MB_SINGBOX_OUT_MARK=169
# IP分流/白名单相关变量
readonly MB_IPSET_NAME="merlinkbox_chn"
readonly MB_IPSET_NAME_V6="merlinkbox_chn_v6"
readonly MB_CHN_IP4_FILE="${CUR_DIR}/res/chn-ip4.txt"
readonly MB_CHN_IP4_WHITELIST_FILE="${CUR_DIR}/res/chn-ip4-whitelist.txt" #这里面的东西不会被代理
readonly MB_CHN_IP6_FILE="${CUR_DIR}/res/chn-ip6.txt"
readonly MB_CHN_IP6_WHITELIST_FILE="${CUR_DIR}/res/chn-ip6-whitelist.txt" #这里面的东西不会被代理
# 是否启用 IPv6 支持 (0 DISABLE, 1 ENABLE)。注意系统会检测到 IPv6 是否可用，如果不可用则会自动禁用 IPv6 支持
MB_ENABLE_IPV6=1
# 屏蔽来自局域网的QUIC协议访问 (0 不屏蔽, 1 屏蔽)
readonly MB_DISABLE_QUIC_FROM_LAN=1

# 引入fun.sh脚本, ./sh/fun.sh
if [ -f "$CUR_DIR/sh/fun.sh" ]; then
    . "$CUR_DIR/sh/fun.sh"
fi

# ==========================================
# 显示帮助信息
# ==========================================
show_help() {
	cat <<EOF
用法:
  $SCRIPT_NAME <command>

命令:
  start        启动服务
  stop         停止服务
  tool         工具命令

工具子命令:
  compress_singbox  压缩 sing-box 可执行文件

选项:
  -h, --help   显示帮助信息
  -v, --version 显示脚本版本
EOF
}

#=========================================
# 显示版本信息
#=========================================
show_version() {
	echo "$SCRIPT_NAME version $SCRIPT_VERSION"
}

#=========================================
# 启动服务
#=========================================
start() {
	print_line "start merlin-box"

  # 如果已经启用IPV6支持，使用 check_ipv6_support 函数检测当前路由是否支持IPv6，如果不支持则禁用IPv6支持
  if [ "$MB_ENABLE_IPV6" -eq 1 ]; then
    if ! check_ipv6_support; then
      echo "[WARN] 当前路由器不支持或已弃用 IPv6，自动禁用 IPv6 支持。"
      MB_ENABLE_IPV6=0
    fi
  fi

	# 清理iptables规则
	reset_iptables
  # 启动singbox socks:65001  tproxy:65002
  start_singbox
  # 启动smartdns服务
	start_smartdns
  # 重启dnsmasq服务
  restart_dnsmasq
  # 完成
	print_line "merlin-box complete"
}

#=========================================
# 停止服务
#=========================================
stop() {
	print_line "stop merlin-box"
	stop_singbox
	stop_smartdns
	clear_iptables
	restart_dnsmasq
	print_line "merlin-box stopped"
}

#=========================================
# 重启服务
#=========================================
restart() {
  stop_singbox
  stop_smartdns
  clear_iptables
  start
}

#=========================================
# 测试函数
#=========================================
test() {
	#reset_iptables
	#clear_iptables
	#start_singbox
	#start_smartdns
	:
}

#=========================================
# 生成启动脚本 & 将 当前脚本放在 /jffs/scripts/wan-start 中以便每次拨号后自动启动
#=========================================
install() {
  print_line "install merlin-box"

  # 目标启动脚本的绝对路径
  local boot_script="${CUR_DIR}/start_merlin_box.sh"
  # 梅林固件的标准服务启动脚本
  local merlin_services_start="/jffs/scripts/wan-start"

  echo "creating boot script"

  # A. 在当前目录下生成启动脚本
  cat << EOF > "${boot_script}"
#!/bin/sh
# Auto-generated by merlin-box installer
cd "${CUR_DIR}"
./merlin-box.sh restart
EOF

  # 赋予生成的脚本执行权限
  chmod +x "${boot_script}"

  # B. 检查并开启梅林固件的 services-start
  if [ ! -f "${merlin_services_start}" ]; then
    echo "Creating merlin services-start script"
    echo "#!/bin/sh" > "${merlin_services_start}"
    chmod +x "${merlin_services_start}"
  fi

  echo "Adding boot script to merlin services-start"

  # C. 将脚本的绝对路径放入 services-start（先清理旧的，防止重复写入）
  # 使用 sed 安全删除已存在的历史写入，然后追加新行，注意末尾加 & 避免阻塞开机
  sed -i "\|${boot_script}|d" "${merlin_services_start}"
  echo "${boot_script} &" >> "${merlin_services_start}"

  print_line "merlin-box installed"
}

#=========================================
# 卸载启动脚本 & 删除 /jffs/scripts/wan-start 中的
#=========================================
uninstall() {
  print_line "uninstall merlin-box"

  local boot_script="${CUR_DIR}/start_merlin_box.sh"
  local merlin_services_start="/jffs/scripts/wan-start"

  # A. 从 /jffs/scripts/wan-start 中删除对应行
  if [ -f "${merlin_services_start}" ]; then
    echo "Removing boot line from merlin wan-start"
    # 使用 sed 删除包含该脚本路径的行（| 作为定界符，防止路径中的 / 冲突）
    sed -i "\|${boot_script}|d" "${merlin_services_start}"
  fi

  # B. 删除当前目录下生成的启动脚本
  if [ -f "${boot_script}" ]; then
    echo "Removing generated boot script..."
    rm -f "${boot_script}"
  fi

  print_line "merlin-box uninstalled"
}

#=========================================
#调用 compress_executable_with_upx 压缩sing-box 可执行文件
#=========================================
compress_singbox() {
  local singbox_path="${CUR_DIR}/bin/sing-box"
  compress_executable_with_upx "$singbox_path"
}

#=========================================
# 主函数
#=========================================
main() {
	if [ "$#" -lt 1 ]; then
		echo "错误: 必须传入参数。"
		show_help
		exit 1
	fi

  # 根据传入的参数执行相应的操作
	case "$1" in
	  install)
  		install
  		;;
  	uninstall)
			uninstall
			;;
		test)
			test
			;;
		start)
			start
			;;
		stop)
			stop
			;;
    tool)
      case "$2" in
        compress_singbox)
          compress_singbox
          ;;
        -h|--help|"")
          echo "用法: $SCRIPT_NAME tool <subcommand>"
          echo "可用子命令: compress_singbox"
          ;;
        *)
          echo "错误: 不支持的工具子命令 '$2'"
          echo "可用子命令: compress_singbox"
          exit 1
          ;;
      esac
      ;;
	  restart)
			restart
			;;
		-h|--help)
			show_help
			;;
		-v|--version)
			show_version
			;;
		*)
			echo "错误: 不支持的参数 '$1'"
			show_help
			exit 1
			;;
	esac
}

main "$@"
