# UDP 监听（默认）
bind [::]:53

# TCP 监听
bind-tcp [::]:53

# 配置一个代理
proxy-server socks5://127.0.0.1:65001 -name socks5

# 屏蔽域名列表
domain-set -name block -file ../res/site-blocklist.txt
# 一个黑名单 必须走代理的域名列表
domain-set -name blacklist -file ../res/site-blacklist.txt
# 配置一个中国大陆的域名列表 仅当前文件中的域名使用china解析, 其它一律使用国外解析
domain-set -name chnlist -file ../res/chn-site.txt

# 屏蔽域名解析为127.0.0.1
address /domain-set:block/#

# 中国大陆域名使用中国DNS解析，其他域名使用国外DNS解析
domain-rules /domain-set:chnlist/ -nameserver china
# 黑名单域名使用国外DNS解析 后面的优先级更高, 域名同时存在chnlist和blacklist中, 也会使用国外DNS解析
domain-rules /domain-set:blacklist/ -nameserver foreign
# 其它域名使用国外DNS解析
domain-rules /./ -nameserver foreign

# 禁用ipv6
# force-AAAA-SOA yes
# 禁用测速
speed-check-mode none
# 启用双栈优选
#dualstack-ip-selection yes

# aliyun dns
server 223.5.5.5 -g china -exclude-from-default-group
# dns pod
server 119.28.28.28 -g china -exclude-from-default-group

# cloudflare dns
server-https https://1.1.1.1/dns-query -proxy socks5 -group foreign
# google dns
server-https https://8.8.8.8/dns-query -proxy socks5 -group foreign
